Usage: .action [action name] [kline|skline|dline|ircwarn|dccwarn] [duration] [reason]

 This command is used to dynamically configure the behavior of the tcm.

 Valid actions are:
  cflood - connection flooders
  vclone - virtual host clones
  flood  - flooders
  link   - link lookers
  spam   - spambots
  clone  - cloners
  rclone - reconnect clones
  nflood - nickname flooders
  jupe   - repeated attempts to join a juped channel
  sclone - services reported clones
  drone  - services reported drones
